# Generated by Django 2.1.5 on 2020-03-17 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doggie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='Comments Content')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Time')),
                ('belong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dogs_comments', to='doggie.Dog', verbose_name='Belongto')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Reviewer')),
            ],
            options={
                'verbose_name': 'Comments',
                'verbose_name_plural': 'Comments',
                'ordering': ['create_date'],
            },
        ),
    ]
